scalar DateTime
type User {
  id: String!
  name: String!
  seller: Boolean!
  created_at: DateTime!
}
type AuthToken {
  id: String!
  name: String!
  token: String!
}
input LoginUser {
  email: String!
  password: String!
}
input RegisterUser {
  email: String!
  password: String!
  password_confirmation: String!
  name: String!
  seller: Boolean!
}
type Query {
  users: [User!]
  me: User!
}
type Mutation {
  login(data: LoginUser!): AuthToken!
  register(data: RegisterUser!): User!
}
